### ISSUE TITLE
OpenJDK Compilation Failed

### ISSUE THREAD

**Issue by aulospl** [richardwilkes/gcs#222]
GCS failed to compile with OpenJDK 14.0.1.

![image](https://user-images.githubusercontent.com/12572896/85954991-f0b36680-b951-11ea-8de0-80eee575feca.png)

Operating System: Arch Linux
KDE Plasma Version: 5.19.2
KDE Frameworks Version: 5.71.0
Qt Version: 5.15.0
Kernel Version: 5.4.49-1-lts
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by richardwilkes** [comment]
That's not a compilation problem, that's a packaging problem. GCS's bundler only knows how to make .deb files -- and if your OS doesn't have the right tools for that, you won't be able to bundle the app.

**Comment by aulospl** [comment]
Why have you stopped releasing a .jar version? Wouldn't it be easier than to bundle to different formats?

**Comment by richardwilkes** [comment]
I stopped that practice quite a long time ago, as too many people just couldn't cope with it. Nothing stopping you from building it, though -- just need to tweak the packing portion of the build to stop after linking it all together, most likely. I haven't tried this, but you can probably remove everything in this function from this line on: https://github.com/richardwilkes/gcs/blob/master/bundler/bundler/Bundler.java#L593 to stop the part that's failing.

**Comment by richardwilkes** [comment]
I don't have any plans to produce installers other than .deb files for the time being. If I can get specific instructions on how to do the desktop integration that it provides on my own, I might be persuaded to roll my own non-distribution-specific package... however, from what I've been able to determine, Linux has a confusing mess of conflicting standards in this area, making it difficult to do anything reasonable without packaging things for each distro. Given the wide array of those out there, that will not happen.

**Comment by AlphaJack** [comment]
Thank you, the new flag will surely help people to build the package for different architectures from source.
Although not my original idea, I found a way to package gcs for x86_64 from the .deb you release, it's now up in the [AUR](https://aur.archlinux.org/packages/gcs/).
